language: python
python:
- '2.7'
- '3.3'
- '3.4'
- pypy

install:
  - pip install -r requirements.txt
  - pip install -r requirements/development.txt
  - pip install coveralls

script: nose2 -v --with-cov

after_success:
  - coveralls
